# Generated by Django 4.1.2 on 2023-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testname', models.CharField(max_length=200)),
                ('testage', models.TextField()),
                ('tesslk', models.TextField()),
            ],
        ),
    ]
