# Generated by Django 4.1.2 on 2023-04-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='tesslk',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='testage',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='Testname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
