# Generated by Django 4.1.2 on 2023-04-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tesslk_test_content_rename_testage_test_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='email',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='test',
            name='password',
        ),
    ]
